### PR TITLE
Bump quic-go

### PR DESCRIPTION
**Pull request by leonrinkel**
See https://github.com/netsec-ethz/scion-apps/issues/239. This PR bumps lucas-clemente/quic-go@v0.23.0 to quic-go/quic-go@v0.34.0. This also causes the project to build and only(!) build with more recent versions of Go. I tested Go 1.19.x and Go 1.20.x, as this is what quic-go claims to support. We'd also have to change README, CI, ... to account for that.

There were two other breaking changes that I had to mitigate:
- `quic.Session` and `quic.EarlySession` were renamed to `quic.Connection` and `quic.EarlyConnection` respectively. I replaced occurrences.
- `KeepAlive: bool` in quic.Config now is `KeepAlivePeriod: time.Duration`. I replaced occurrences of `KeepAlive: true` with `KeepAlivePeriod: time.Duration(15) * time.Second` which is half the default `MaxIdleTimeout` so it should have the same effect as the previous `KeepAlive: true`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/241)

### CODE REVIEW

**Review by marcfrei — CHANGES_REQUESTED** [review]
Thanks for tackling this update too!

Which version of golangci-lint did you use to build (make) this branch? With golangci-lint version 1.53.1 and go1.19.9 I get quite some linter warnings.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-:-NXQaSM81y5h7O0PK6jb:b-urvhqj)* status: all files reviewed, 4 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`_examples/sgrpc/client/main.go` line 34 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NXQ_mV_4ysVOWhAIg9-:-NXQ_mV_4ysVOWhAIg90:b21m6dn) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/c49f0960d3cfe51a353a0ceb75fdcbbbcd4027ef/_examples/sgrpc/client/main.go#L34)):*
> ```Go
> 		}
> 
> 		clientQuicConfig := &quic.Config{KeepAlivePeriod: time.Duration(15) * time.Second}
> ```

Just `15 * time.Second` should work too, right? 



_Code quote:_
```Go
time.Duration(15) * time.Second
```
___
*[`netcat/quic.go` line 44 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NXQa2608PZvUCBs7Kbu:-NXQa2608PZvUCBs7Kbv:b-xoahtq) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/c49f0960d3cfe51a353a0ceb75fdcbbbcd4027ef/netcat/quic.go#L44)):*
> ```Go
> 			NextProtos:   nextProtos,
> 		},
> 		&quic.Config{KeepAlivePeriod: time.Duration(15) * time.Second},
> ```

`15 * time.Second`



_Code quote:_
```Go
time.Duration(15) * time.Second
```
___
*[`netcat/quic.go` line 84 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NXQa5lb6rabFFkiuopf:-NXQa5lb6rabFFkiuopg:b-xoahtq) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/c49f0960d3cfe51a353a0ceb75fdcbbbcd4027ef/netcat/quic.go#L84)):*
> ```Go
> 			NextProtos:         nextProtos,
> 		},
> 		&quic.Config{KeepAlivePeriod: time.Duration(15) * time.Second},
> ```

`15 * time.Second`



_Code quote:_
```Go
time.Duration(15) * time.Second
```
___
*[`ssh/client/ssh/scion.go` line 50 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NXQaGDv46TCz70FhDpy:-NXQaGDv46TCz70FhDpz:b-xoahtq) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/c49f0960d3cfe51a353a0ceb75fdcbbbcd4027ef/ssh/client/ssh/scion.go#L50)):*
> ```Go
> 	}
> 	quicConf := &quic.Config{
> 		KeepAlivePeriod: time.Duration(15) * time.Second,
> ```

`15 * time.Second`



_Code quote:_
```Go
time.Duration(15) * time.Second
```

**Comment by leonrinkel** [comment]
Didn't use linting, I'll have a look

**Comment by leonrinkel** [comment]
Ok so I did some changes to please the linter (latest version 1.53.2). Most are minor formatting changes that the linter did automatically with `--fix` ([d2db466](https://github.com/netsec-ethz/scion-apps/pull/241/commits/d2db466e6a52535902b4ee36d0e9afbce3f407db)). There are some changes related to quic http3 which I previously missed ([d453008](https://github.com/netsec-ethz/scion-apps/pull/241/commits/d45300829419276b1ffd9a383fb743fa4ce57b2f)). And finally added `//nolint:contextcheck` in some places where I honestly wasn't sure and felt like actually passing context down there would change too much of the logic ([f858307](https://github.com/netsec-ethz/scion-apps/pull/241/commits/f8583073a067b1f5e66236168d3da73d10545098)), please have a look into that.

**Comment by marcfrei** [comment]
Thanks a lot, Leon! I'll try and take another look at this later this week.

**Comment by marcfrei** [comment]
I just tried to build the PR on a fresh Ubuntu 22.04 instance with the following commands and I still get linter warnings and errors:

```
curl -LO https://golang.org/dl/go1.19.10.linux-amd64.tar.gz
echo "8b045a483d3895c6edba2e90a9189262876190dbbd21756870cdd63821810677 go1.19.10.linux-amd64.tar.gz" | sha256sum -c
sudo tar -C /usr/local -xzf go1.19.10.linux-amd64.tar.gz
echo >> .bash_profile
echo 'export PATH=$PATH:/usr/local/go/bin' >> .bash_profile
source ~/.bash_profile

curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.53.3
echo >> .bash_profile
echo 'export PATH=$PATH:~/go/bin' >> .bash_profile
source ~/.bash_profile

sudo apt-get update
sudo apt-get install -y build-essential libpam0g-dev

git clone https://github.com/leonrinkel/scion-apps.git
cd scion-apps
git rev-parse HEAD
go version
golangci-lint --version
make
```

Does this work in your setup?

**Comment by leonrinkel** [comment]
Oops, I missed that just using `golangci-lint run` does not check the `_examples` directory. I now committed minor formatting changes for `_examples` too. Sorry for the inconvenience.

**Review by marcfrei — CHANGES_REQUESTED** [review]
- Comment out ifshort in `.golangci.yml` and `_examples/.golangci.yml` to avoid deprecation warnings.

Other open points:
- Update target `setup_lint` in Makefile
- Update README, CI, ...

Additional question:
- Would you like to tackle the update to quic-go v0.35.1 (https://github.com/quic-go/quic-go/releases/tag/v0.35.0 and https://github.com/quic-go/quic-go/releases/tag/v0.35.1) as part of this PR too?

> Reviewed 2 of 3 files at r2, 17 of 17 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-:-NYMjHv14KUIxNXouDMl:bbsbhax)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`pkg/pan/pan.go` line 27 at r4](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NYMf8FjEclB0Ygq1zFw:-NYMf8FjEclB0Ygq1zFx:bq64hhd) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/7355bb9b41c6788c4d7247a551e59d747ff3a7c4/pkg/pan/pan.go#L27)):*
> ```Go
> 
> # Policy
> # Policy
> ```

Duplicate line. Intentionally? See also changes below.

**Comment by leonrinkel** [comment]
Sorry for taking so long! I didn't want to update to quic-go v0.35.1 already since there are even more breaking changes and I wanted to keep this PR smaller/simpler. CI build does work now, however the integration task does not. I'm not familiar with CircleCI and not sure what to do there, what machine type has what Go version etc.

**Comment by marcfrei** [comment]
Great thanks, Leon! I'll take another look at this later this week.

**Review by marcfrei — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/241)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`.circleci/config.yml` line 39 at r5](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-NZ_t-Pa-qn_sajQ48kM:-NZ_t-Pb2hD9Rj5xAz--:b-hatluc) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0c39e4d83a23e3ba0ec4014e79c37e31cec3e42d/.circleci/config.yml#L39)):*
> ```YAML
>   integration:
>     machine:
>       image: ubuntu-2004:202111-02 # using go1.17.3
> ```

According to https://circleci.com/developer/machine/image/ubuntu-2004

the most recent tag is `ubuntu-2004:2023.04.2` which should contain Go 1.20.2:

https://discuss.circleci.com/t/linux-machine-executor-2023-q2-update-edge-ga-release/47680

**Comment by leonrinkel** [comment]
Uhh ok so integration tries to build scionproto/scion which apparently also is not compatible with recent Go versions. We could build scion and scion-apps with separate Go versions in the integration task or set this PR aside for now till scionproto/scion also updates to more recent Go versions.

**Comment by matzf** [comment]
Note that you're having issues to build the SCION binaries with go 1.19 because it's trying to build a very old version. If you build a recent version, it will work.
The version of SCION built in the CI is selected based on the dependency version in go.mod (see `.circleci/config.yml:48-54`). This has been convenient and useful to keep things working when there were incompatible changes upstream. However, it's not really not strictly necessary to build the same version that is used as dependency for the scion-apps. As an alternative to what Marc suggested above, you can decouple this by setting `scion_commit` to some specific, recent commit sha. Note that you'll also have to adapt the paths used for the `go build` commands (as the paths and names of the binaries have changed).

**Comment by martenwallewein** [comment]
Hey guys,

thanks for your help and your feedback to this PR! Today Leon and I discussed that it would be great to complete this one so that he can move further with his work on IPFS over SCION. I like the idea of setting a particular scion commit to build the newest version, but looking into this, more issues than replacing the go build command popped up and need to be fixed (e.g. the location of the topology generation script changed and needs to be adapted). I haven't checked all potential changes, but there may be some more (and also scion currently only builds for go 1.19, not 1.20).

So I would suggest to follow Marc's idea to build the current SCION binaries with go 1.17 and scion-apps with 1.19/20 by installing two different versions of Go. Since Leon and I are not super deep into circle-ci, could one of you check a potential change via these orbs that Marc suggested? If you don't have any ressources for this, I would suggest to change the Go version by just downloading/installing it into the ubuntu container used for integration tests, e.g. 

```
wget https://go.dev/dl/go1.20.7.linux-amd64.tar.gz
rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.7.linux-amd64.tar.gz
```

If we decide to follow this simple approach, @leonrinkel could you give it a try, since it's your PR? BTW thanks for all your effort for this so far!

I think adapting the CI to the newest SCION version is a dedicated issue, which is good to tackle, but in my opinion out of scope for Leon. Wish you all a nice weekend!

**Comment by marcfrei** [comment]
Thanks, Marten.

> I would suggest to change the Go version by just downloading/installing it into the ubuntu container used for integration tests, e.g.
>
> wget https://go.dev/dl/go1.20.7.linux-amd64.tar.gz
> rm -rf /usr/local/go && tar -C /usr/local -xzf go1.20.7.linux-amd64.tar.gz

Yes, agreed, that's probably the simplest approach indeed. @leonrinkel, if you get it running like this, we could then look into the CircleCi orbs feature and/or setting a specific SCION commit like Matthias suggested in separate follow-up PR.

**Comment by leonrinkel** [comment]
Ok I reverted to the original CI machine image, since there were version issues with Python too. I am now building scionproto/scion with the original Go 1.17.3 and then installing Go 1.20.7 to proceed with integration testing, as @martenwallewein suggested. This seems to work now.

**Review by marcfrei — APPROVED** [review]
:lgtm:

Thanks a lot for this, Leon!

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/241#-:-Nbk0vVQ8cCH2dp-1Lkt:b1qdhqk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by martenwallewein** [comment]
Thank you for your effort guys, awesome that it is now merged! :rocket:

**Pull request merged**
