### PR TITLE
Bump SCION to current scionproto/scion:master

### PR DESCRIPTION
**Pull request by marcfrei**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/166)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/166)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @marcfrei and @matzf)

___
*[ssh/scionutils/policy_conn_test.go, line 99 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYtEZeDYX4jDv9Ltyh:-MIYtEZeDYX4jDv9Ltyi:b-et0gtc) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L99)):*
> ```Go
> 	paths := makePaths(5)
> 	pathSet := make(pathpol.PathSet)
> 	pathSet[snet.Fingerprint(paths[1])] = nil
> ```

Nit, I think this could now assign `paths[1]` instead of the (nonsensical) `nil`. Not completely sure though.
___
*[ssh/scionutils/policy_conn_test.go, line 118 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYtswFAwAX54yfmO_5:-MIYtswFAwAX54yfmO_6:bmi8ppe) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L118)):*
> ```Go
> // mockPath satisfies the snet.Path interface but does not actually
> // implement anything. This allows to check object identities, as
> // defined by snet.Fingerprint.
> ```

:100: 
___
*[ssh/scionutils/policy_conn_test.go, line 127 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYsu-t0UweN6XUF0zb:-MIYsu-t0UweN6XUF0zc:bb223cw) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L127)):*
> ```Go
> func (p *mockPath) Interfaces() []snet.PathInterface { return p.interfaces }
> func (p *mockPath) Destination() addr.IA             { return addr.IA{} }
> func (p *mockPath) Metadata() snet.PathMetadata      { return p }
> ```

Just `return nil` and remove the dummy `MTU` and `Expiry` (it's irrelevant).
___
*[ssh/scionutils/policy_conn_test.go, line 153 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYscJ55KL974ynJXj-:-MIYscJ55KL974ynJXj0:b92ipzc) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L153)):*
> ```Go
> 
> func (i mockPathInterface) ID() common.IFIDType { return i.id }
> func (i mockPathInterface) IA() addr.IA         { return addr.IA{} }
> ```

This can go now, https://github.com/scionproto/scion/pull/3879 just merged.
___
*[webapp/lib/sciond.go, line 275 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYplafD0t84MZ6dWdO:-MIYplafD0t84MZ6dWdP:b-whptpc) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/webapp/lib/sciond.go#L275)):*
> ```Go
> 	}
> 	if len(paths) > 10 {
> 		paths = paths[:10]
> ```

Any particular reason for this?

**Comment by marcfrei** [comment]
___
*[ssh/scionutils/policy_conn_test.go, line 99 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYtEZeDYX4jDv9Ltyh:-MIZ-mmH1V3Ccd1OTu14:b-ad8ywn) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L99)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit, I think this could now assign `paths[1]` instead of the (nonsensical) `nil`. Not completely sure though.
</blockquote></details>

Ah, yes, of course..

**Comment by marcfrei** [comment]
___
*[webapp/lib/sciond.go, line 275 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYplafD0t84MZ6dWdO:-MIZ0NHu5pCeUBcYEgXA:b-cb5la3) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/webapp/lib/sciond.go#L275)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Any particular reason for this?
</blockquote></details>

To replicate the old behavior with `sciond.PathReqFlags{PathCount: 10}`. Should we keep this or remove it?

**Comment by marcfrei** [comment]
___
*[ssh/scionutils/policy_conn_test.go, line 153 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYscJ55KL974ynJXj-:-MIZ5SIZ2YeC0Eb5GZK5:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/ssh/scionutils/policy_conn_test.go#L153)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This can go now, https://github.com/scionproto/scion/pull/3879 just merged.
</blockquote></details>

Done.

**Review by matzf — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/166)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @marcfrei and @matzf)

___
*[webapp/lib/sciond.go, line 275 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIYplafD0t84MZ6dWdO:-MIZocdB16W3zaJyDfnE:b4mond7) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/29b55eb549f688f4923d414f72ea81aa38384da8/webapp/lib/sciond.go#L275)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

To replicate the old behavior with `sciond.PathReqFlags{PathCount: 10}`. Should we keep this or remove it?
</blockquote></details>

Ah, of course, missed that change. Funny, this flag was actually ignored, so you can safely remove it :wink:

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/166)* status: all files reviewed, 2 unresolved discussions (waiting on @marcfrei)

___
*[.circleci/config.yml, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIwsfk91693gqxA8B8d:-MIwsfk91693gqxA8B8e:br38zt2) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/b41d1c1d09f1a2f48cb64ece9c1e066b3be0e763/.circleci/config.yml#L65)):*
> ```YAML
>             done
> 
>             sudo apt-get update && sudo apt-get install --assume-yes python3 python3-pip
> ```

It turns out, we have python3 already in the VM, and it's not from the debian package but from some (seemingly undocumented :/) circleci shim that installs python 3.8.1.
Note, this confused me a lot, because the output for the apt install showed that python 3.5.1 was installed for which the topo scripts below are expected to fail.

Could you please remove this `apt` line, and add `python --version` and `go version` somewhere to the beginning to make the version information visible to the log? And perhaps add a note that this is some circleci magic...
___
*[.circleci/config.yml, line 92 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIwwmH62r_1Vpqf3wlC:-MIwwmH73nPU6E3QWxt8:bih1m7x) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/b41d1c1d09f1a2f48cb64ece9c1e066b3be0e763/.circleci/config.yml#L92)):*
> ```YAML
>           command: |
>             # Handle the two special ones
>             curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.31.0
> ```

I guess the reason for this change is that `setup_lint` does not work for the `GOPATH` setup on the circleci executor (multiple directories returned). We can try to fix the Makefile, instead of duplicating this with the problem of potentially (and actually) having different versions. Here's an attempt, patching the existing "machinery" for the installation directory to work with multiple entries in GOPATH:

```
diff --git a/Makefile b/Makefile
index 5b15614..02ea804 100644
--- a/Makefile
+++ b/Makefile
@@ -6,7 +6,8 @@ BIN = bin
 #   environment as returned by go env, and uses the "Default Values" parameter
 #   expansion ${variable:-default} to implement the fallback sequence:
 #     $GOBIN, else $GOPATH/bin, else $HOME/go/bin
-DESTDIR = $(shell set -a; eval $$( go env ); echo $${GOBIN:-$${GOPATH:-$${HOME}/go}/bin})
+#   If there are multiple entries in GOPATH, take the first.
+DESTDIR = $(shell set -a; eval $$( go env ); gopath=$${GOPATH%:*}; echo $${GOBIN:-$${gopath:-$${HOME}/go}/bin})

 # HINT: build with TAGS=norains to build without rains support
 TAGS =
@@ -31,7 +32,7 @@ test: lint

 setup_lint:
        @# Install golangci-lint (as dumb as this looks, this is the recommended way to install)
-       curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $$(go env GOPATH)/bin v1.26.0
+       curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b ${DESTDIR} v1.26.0

 lint:
        @type golangci-lint > /dev/null || ( echo "golangci-lint not found. Install it manually or by running 'make setup_lint'."; exit 1 )
```

**Comment by marcfrei** [comment]
___
*[.circleci/config.yml, line 65 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIwsfk91693gqxA8B8d:-MJf0EBg-8KrcezDoO28:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0422c238c8b0946c135e10b5105f1d3871a3555d/.circleci/config.yml#L65)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It turns out, we have python3 already in the VM, and it's not from the debian package but from some (seemingly undocumented :/) circleci shim that installs python 3.8.1.
Note, this confused me a lot, because the output for the apt install showed that python 3.5.1 was installed for which the topo scripts below are expected to fail.

Could you please remove this `apt` line, and add `python --version` and `go version` somewhere to the beginning to make the version information visible to the log? And perhaps add a note that this is some circleci magic...
</blockquote></details>

Done.

**Comment by marcfrei** [comment]
___
*[.circleci/config.yml, line 92 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIwwmH62r_1Vpqf3wlC:-MJf5yNbCH-7uOKfdW3U:b-ucfknh) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0422c238c8b0946c135e10b5105f1d3871a3555d/.circleci/config.yml#L92)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I guess the reason for this change is that `setup_lint` does not work for the `GOPATH` setup on the circleci executor (multiple directories returned). We can try to fix the Makefile, instead of duplicating this with the problem of potentially (and actually) having different versions. Here's an attempt, patching the existing "machinery" for the installation directory to work with multiple entries in GOPATH:

```
diff --git a/Makefile b/Makefile
index 5b15614..02ea804 100644
--- a/Makefile
+++ b/Makefile
@@ -6,7 +6,8 @@ BIN = bin
 #   environment as returned by go env, and uses the "Default Values" parameter
 #   expansion ${variable:-default} to implement the fallback sequence:
 #     $GOBIN, else $GOPATH/bin, else $HOME/go/bin
-DESTDIR = $(shell set -a; eval $$( go env ); echo $${GOBIN:-$${GOPATH:-$${HOME}/go}/bin})
+#   If there are multiple entries in GOPATH, take the first.
+DESTDIR = $(shell set -a; eval $$( go env ); gopath=$${GOPATH%:*}; echo $${GOBIN:-$${gopath:-$${HOME}/go}/bin})

 # HINT: build with TAGS=norains to build without rains support
 TAGS =
@@ -31,7 +32,7 @@ test: lint

 setup_lint:
        @# Install golangci-lint (as dumb as this looks, this is the recommended way to install)
-       curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $$(go env GOPATH)/bin v1.26.0
+       curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b ${DESTDIR} v1.26.0

 lint:
        @type golangci-lint > /dev/null || ( echo "golangci-lint not found. Install it manually or by running 'make setup_lint'."; exit 1 )
```
</blockquote></details>

Thanks!

**Comment by marcfrei** [comment]
___
*[.circleci/config.yml, line 92 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/166#-MIwwmH62r_1Vpqf3wlC:-MJf63yc-y5qoVgXoxjG:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0422c238c8b0946c135e10b5105f1d3871a3555d/.circleci/config.yml#L92)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Thanks!
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/166)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by marcfrei** [comment]
Replaced by https://github.com/netsec-ethz/scion-apps/pull/171

**Pull request closed without merging**
