### PR TITLE
Bump scionproto and rains dependencies

### PR DESCRIPTION
**Pull request by martenwallewein**
Hey guys, following this issue https://github.com/netsec-ethz/scion-apps/issues/244

to have scion-apps aligned with the newest scionproto and also quic-go version I started to migrate this (or at least to give it a try ^^). It currently waits for this PR https://github.com/netsec-ethz/rains/pull/242 to be merged beforehand, but overall the changes look doable. 

Will keep you in loop!

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/246)

### CODE REVIEW

**Review by marcfrei — CHANGES_REQUESTED** [review]
Thanks for starting this @martenwallewein. Some first comments below.

> Reviewed 23 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-:-NgrhaG-6Rjppw2qkvay:br6kddl)* status: 23 of 25 files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`go.mod` line 24 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-Ngr_JgM6KiJ-rVUQjS3:-Ngr_JgM6KiJ-rVUQjS4:b492s2k) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/go.mod#L24)):*
> ```XML
> )
> 
> // replace github.com/netsec-ethz/rains => ../rains/
> ```

Remember to remove this again before finalizing the PR.
___
*[`pkg/pan/path.go` line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-Ngra3K75PH-huRTvPGe:-Ngra3K75PH-huRTvPGf:b-jg25ju) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/path.go#L32)):*
> ```Go
> type Path struct {
> 	source         IA
> 	destination    IA
> ```

What's the reason for this change?



_Code quote:_
```Go
	source         IA
	destination    IA
```
___
*[`pkg/pan/policy.go` line 188 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgraXAi6AsZunCxvnrz:-NgraXAi6AsZunCxvns-:b-ee8h5k) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/policy.go#L188)):*
> ```Go
> func (p snetPathWrapper) Destination() addr.IA          { panic("not implemented") }
> 
> // TODO: I'm not sure if it's fine to panic here...
> ```

Remember to clean this up again before finalizing the PR.
___
*[`pkg/pan/quic_listen.go` line 61 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgraklO43ljpwOC7R7v:-NgraklP9Afds-u_roob:b-xvsyn7) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/quic_listen.go#L61)):*
> ```Go
> 	//	Listener: listener,
> 	//	conn:     conn,
> 	//}, nil
> ```

Remove this old code, history will be preserved by Git.
___
*[`pkg/pan/raw.go` line 110 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgrfgBR71BFjNCcqP5L:-NgrfgBR71BFjNCcqP5M:b-kzs9tt) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/raw.go#L110)):*
> ```Go
> 			Source: snet.SCIONAddress{
> 				IA:   addr.IA(src.IA),
> 				Host: addr.MustParseHost(src.IP.IPAddr().IP.String()),
> ```

It's good to have PRs that focus on single issue but here I think the correct way to handle this is to go ahead and replace inet.af/netaddr by net/netip like in https://github.com/scionproto/scion/commit/c43f942cc59aa2687f60e7cdddf8212bf52a2987

**Comment by sarcasticadmin** [comment]
@martenwallewein building the latest on this branch works for me and the binaries basic functionality (--help) seems good. Nice job!

Consider updating the `_examples/go.{mod,sum}` as well: https://github.com/netsec-ethz/scion-apps/blob/28b48f6c4b4aa806d85ba0051ddab00317a1e3ac/_examples/go.mod

**Comment by matzf** [comment]
@martenwallewein I took the liberty to push to your branch; I've updated the _examples, fixed the lint errors and updated the SCION setup for the integration tests. I think this is ready now.

**Review by matzf — COMMENTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/246)* status: 6 of 63 files reviewed, 5 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`go.mod` line 24 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-Ngr_JgM6KiJ-rVUQjS3:-Ni5-4Jd62gSmJFfj1Va:b-ca9zeb) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/go.mod#L24)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remember to remove this again before finalizing the PR.
</blockquote></details>

Done, by Marten
___
*[`pkg/pan/path.go` line 32 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-Ngra3K75PH-huRTvPGe:-Ni4netc8pZ7I4WCN0Tz:bbyjzlh) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/path.go#L32)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

What's the reason for this change?
</blockquote></details>

Done, reverted. Was probably a change due to a somewhat confusing wrapper to use `pan.Path` as `snet.Path`.
___
*[`pkg/pan/policy.go` line 188 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgraXAi6AsZunCxvnrz:-Ni4oWUlBPlRBneUv79X:b-pp17en) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/policy.go#L188)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remember to clean this up again before finalizing the PR.
</blockquote></details>

Done, by Marten.
___
*[`pkg/pan/quic_listen.go` line 61 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgraklO43ljpwOC7R7v:-Ni4oaqR-U70_eeNWdlq:b-pp17en) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/quic_listen.go#L61)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove this old code, history will be preserved by Git.
</blockquote></details>

Done, by Marten.
___
*[`pkg/pan/raw.go` line 110 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-NgrfgBR71BFjNCcqP5L:-Ni4ovcT9pERCbRsa79l:b9zjg8i) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/a5bc8f88b1117621a6cc7272a06423cba2ba7ed5/pkg/pan/raw.go#L110)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

It's good to have PRs that focus on single issue but here I think the correct way to handle this is to go ahead and replace inet.af/netaddr by net/netip like in https://github.com/scionproto/scion/commit/c43f942cc59aa2687f60e7cdddf8212bf52a2987
</blockquote></details>

Done. This is a relatively big change, please review!

**Comment by sarcasticadmin** [comment]
@matzf thanks for updating `_examples`. Im able to build and basic functionality looks good on my end.

My build environment:

```
$ go version
go version go1.21.3 linux/amd64
```

A few tests of the tools inside SCiONLabs:

`bwtestserver`:

```
$ ./result/bin/scion-bwtestserver --listen=:30100
Received request: N 18-ffaa:1:10bf,127.0.0.1:35319
Received request: R 18-ffaa:1:10bf,127.0.0.1:35319
```

`bwtestclient`:

```
 $ ./result/bin/scion-bwtestclient -s 18-ffaa:1:10a0,127.0.0.1:30100 -cs 10,1000,1250,1Mbps -sc 10,1000,12500,10Mbps

Test parameters:
client->server: 10 seconds, 1000 bytes, 1250 packets
server->client: 10 seconds, 1000 bytes, 12500 packets

S->C results
Attempted bandwidth: 10000000 bps / 10.00 Mbps
Achieved bandwidth: 9975200 bps / 9.98 Mbps
Loss rate: 0.2%
Interarrival time min/avg/max/mdev = 0.002/0.802/46.580/6.766 ms

C->S results
Attempted bandwidth: 1000000 bps / 1.00 Mbps
Achieved bandwidth: 1000000 bps / 1.00 Mbps
Loss rate: 0.0%
Interarrival time min/avg/max/mdev = 0.005/8.007/60.863/7.270 ms
```
---

`helloquic` server:

```
$ ./result/bin/example-helloquic -listen 127.0.0.1:9000
18-ffaa:1:10bf,127.0.0.1:9000
New session 18-ffaa:1:10a0,127.0.0.1:34776
hi dude, 0
```

`helloquic` client:
```
$ ./result/bin/example-helloquic -remote  18-ffaa:1:10bf,127.0.0.1
:9000
gotcha: hi dude, 0
```

**Comment by martenwallewein** [comment]
> @martenwallewein I took the liberty to push to your branch; I've updated the _examples, fixed the lint errors and updated the SCION setup for the integration tests. I think this is ready now (except for Marc's comments, that is).

Hey @matzf, thanks a lot for picking this up! I was on vacation until today and didn't had a chance to look at this since my last commit. Since I was quite lost with some changes, especially to PAN, I really appreciate that you tackled these issues! Looking forward to have scion-apps running the latest scion version! :partying_face:

**Comment by sarcasticadmin** [comment]
Is there anything left to do before getting this merged?

**Comment by matzf** [comment]
From my side, this is complete, pending @marcfrei's review.

I left a "BUG" comment on the pan.ListenQUIC API, which is now somewhat broken, because it can no longer properly close the underlying socket. The issue is that the quic-go library changed the listener from an interface type to a struct, which cannot be wrapped as easily. This is probably not a huge practical problem as our demo applications only open one listener for the duration of the program. 
The API should be cleaned up eventually though, perhaps ideally just getting rid of the ListenQUIC helper and leaving this up to the applications.

**Review by marcfrei — APPROVED** [review]
:lgtm: @martenwallewein: what do you think, should I merge the PR?

> Reviewed 17 of 25 files at r3, 1 of 1 files at r4, 39 of 39 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/246#-:-NiaKTGF790EwOsXnrqA:b7h0362)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by matzf** [comment]
The only use of drkey in the scion-apps was the `_examples/hellodrkey`, which I've deleted here, as it is now maintained in scionproto/scion as demo/drkey.
I don't want to disregard the discussion in #244, but I think with this example code gone, there is no problem to merge this directly to master.

**Comment by martenwallewein** [comment]
> The only use of drkey in the scion-apps was the `_examples/hellodrkey`, which I've deleted here, as it is now maintained in scionproto/scion as demo/drkey. I don't want to disregard the discussion in #244, but I think with this example code gone, there is no problem to merge this directly to master.

Perfect, so no objections from me to merge into master :+1:

**Review by marcfrei — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/246)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
