### PR TITLE
pan: add ACL policy

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR add the ACL policy following the ACL pattern in https://scion.docs.anapaya.net/en/latest/PathPolicy.html#acl

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/212)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/212)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/policy.go, line 135 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/212#-Mq08NPCAKnX_YkDQiEv:-Mq08NPCAKnX_YkDQiEw:b-385zvd) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/46471a2724df4e6655cb04b006be18ba6f0ce443/pkg/pan/policy.go#L135)):*
> ```Go
> 		aclEntry := &pathpol.ACLEntry{}
> 		if err := aclEntry.LoadFromString(entry); err != nil {
> 			return ACL{}, serrors.WrapStr("parsing ACL entries", err)
> ```

Avoid using SCION internal serrors library. Just `fmt.Errorf("parsing ACL entries: %w", err)`

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/212)* status: 1 of 2 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/policy.go, line 135 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/212#-Mq08NPCAKnX_YkDQiEv:-MqmjhQP5GJOL5sgvwoC:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/46471a2724df4e6655cb04b006be18ba6f0ce443/pkg/pan/policy.go#L135)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Avoid using SCION internal serrors library. Just `fmt.Errorf("parsing ACL entries: %w", err)`
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Comment by matzf** [comment]
Rebased

**Pull request merged**
