### PR TITLE
Support latest SCIONLab biweekly update.

### PR DESCRIPTION
**Pull request by juagargi**
No spath library.
Removed methods from Path and ForwardingPath that were unused. (Copy, Reversed)
addr.IA is now an uint64.
Addresses of snet.UDPAddr type must beware of its Path not being nil.

TODO:
- [x] Merge rains PR https://github.com/netsec-ethz/rains/pull/240
- [x] Merge netsec-ethz/scion PR https://github.com/netsec-ethz/scion/pull/110
- [x] Point to the correct commits for netsec-ethz/scion:scionlab and rains in `go.mod`

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: all files reviewed, 15 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/addr.go, line 112 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwjzyQN5WCdwA775dA7:-MwjzyQN5WCdwA775dA8:b7pm3v) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L112)):*
> ```Go
> type IA addr.IA
> 
> func IAFrom(isd addr.ISD, as addr.AS) (IA, error) {
> ```

We don't need this. The tests that have previously constructed an `IA` directly should just use `MustParseIA`. As far as I remember, the IA was only constructed directly because at the time this `MustParseIA` had not been added yet.
___
*[pkg/pan/addr.go, line 124 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk6SDOCb32U0UA0hj1:-Mwk6SDOCb32U0UA0hj2:b-6lrhw9) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L124)):*
> ```Go
> // IsWildcard reports whether ia has a wildcard part (isd or as, or both).
> func (ia IA) IsWildcard() bool {
> 	return addr.IA(ia).ISD() == 0 || addr.IA(ia).AS() == 0
> ```

Or just `addr.IA(ia).IsWildcard()`.
___
*[pkg/pan/addr_test.go, line 31 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkB9XU2xmo9cKds8EX:-MwkB9XU2xmo9cKds8EY:b-kjrcfi) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr_test.go#L31)):*
> ```Go
> 	assert.NoError(t, err)
> 	iaWildcard, err := pan.IAFrom(1, 0)
> 	assert.NoError(t, err)
> ```

Parse from string as suggested above, `ia := pan.MustParseIA("1-ff00:0:ff")` and `iaWildcard := pan.MustParseIA("1-0")`
___
*[pkg/pan/path.go, line 63 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk4IAJAXPdYMlTD1db:-Mwk4IAJAXPdYMlTD1dc:b-gze7u6) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L63)):*
> ```Go
> 	default:
> 		return false
> 	}
> ```

These type checks make me cry a little bit. We'll need to revisit this, these new path types make things even more complicated than before. E.g. there is at least one more way an empty path could be represented (`RawReplyPath` containing a `slayers/path/empty.Path`).

This `IsEmpty` is currently only used internally in pan, only`reversePathFromForwardingPath`. Perhaps it would be best to remove this as a public function and so avoid having to make this work for all possible representations of an empty path. 
___
*[pkg/pan/path.go, line 77 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk3fiM1cBmtfUc34hK:-Mwk3fiNDqvDuiHmi9Ul:b-kogr42) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L77)):*
> ```Go
> 			}
> 		}
> 		if dataplanePath.Path.Type() != scion.PathType {
> ```

This `if` can just be the `default:` of the `switch` above.
___
*[pkg/pan/path.go, line 82 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkEX1fC5LcsZE9Coio:-MwkEX1fC5LcsZE9Coip:b-2u8nci) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L82)):*
> ```Go
> 	case snetpath.SCION:
> 		raw = dataplanePath.Raw
> 	default:
> ```

I think this also needs to handle `snet.RawPath`



_Code quote:_
```Go
forwardingPathInfo
```
___
*[pkg/pan/path.go, line 106 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkC1T_CfeOAaFeL0F-:-MwkC1T_CfeOAaFeL0F0:bx83t9w) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L106)):*
> ```Go
> 	rp, ok := fwPath.dataplanePath.(snet.RawPath)
> 	if !ok {
> 		return nil, fmt.Errorf("cannot reverse path type %T", fwPath.dataplanePath)
> ```

Let this `panic` here, we really expect this to be only called with `RawPath`.
Then the `IsEmpty` (removed, see above) can be inlined here by just `len(rp.Raw) == 0`.
___
*[pkg/pan/path.go, line 127 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkEjetCFF8JYbASccN:-MwkEjetCFF8JYbASccO:bfwcvzt) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L127)):*
> ```Go
> }
> 
> func reversePathFingerprint(p snet.DataplanePath) (PathFingerprint, error) {
> ```

This can only be called with an `snet.RawPath`. I think it would help to change the type here accordingly and type assert on the call sites.
___
*[pkg/pan/path.go, line 154 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkCdG36EO0QhVNQcX3:-MwkCdG36EO0QhVNQcX4:byh0sn1) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L154)):*
> ```Go
> 		seglen := int(sp.Base.PathMeta.SegLen[i])
> 		for h := 0; h < seglen; h++ {
> 			exp := hopExpiry(&info, &sp.HopFields[hop])
> ```

Rather change the signature of the function above to take these as values instead of pointers.
___
*[pkg/pan/path.go, line 189 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkCq9YAm4mKFeg5Yov:-MwkCq9YAm4mKFeg5Yow:b-v1vjpj) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L189)):*
> ```Go
> 		for h := 0; h < seglen; h++ {
> 			if h > 0 || (info.Peer && i == 1) {
> 				ifIDs = append(ifIDs, first(&sp.HopFields[hop], info.ConsDir))
> ```

Also here, change the signature of `first` and `second` to take hf by value.
___
*[pkg/pan/internal/ping/ping.go, line 147 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkF3uNDwRiUw8jthOi:-MwkF3uO1f9ofQdbetIX:b-hvtdqs) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/internal/ping/ping.go#L147)):*
> ```Go
> 	Received time.Time
> 	Source   snet.SCIONAddress
> 	Path     snet.DataplanePath
> ```

This will always be `snet.RawPath`. Maybe we can make this explicit here (type assert when filling the struct).
___
*[pkg/pan/internal/ping/ping.go, line 169 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkFt1LEJxhIOkb_JjL:-MwkFt1LEJxhIOkb_JjM:b5rtile) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/internal/ping/ping.go#L169)):*
> ```Go
> type InternalConnectivityDownError struct {
> 	snet.SCMPInternalConnectivityDown
> 	Path snet.DataplanePath
> ```

It turns out these `Path` members are actually not used (we only inspect the `Path` of the `Reply` struct instead) and can be removed.
___
*[webapp/lib/sciond.go, line 196 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk5QiD2k9hhGJz-pFY:-Mwk5QiD2k9hhGJz-pFZ:b-7gj63) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/lib/sciond.go#L196)):*
> ```Go
> 		return filenames[0]
> 	}
> 	ia.AS()
> ```

Left over debug statement?
___
*[webapp/models/path/segments.go, line 40 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkHE93E8t0SH8eCp5A:-MwkHE93E8t0SH8eCp5B:b-t6rhtt) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/models/path/segments.go#L40)):*
> ```Go
> 	ia, _ := addr.IAFrom(isd, as) // ignore error
> 	return asIface{IA: ia, IfNum: ifNum}
> }
> ```

Just remove this function?
In two cases, using this function only makes things longer because the existing IA is split into ISD/AS first.
In the third case, the error from `IAFrom` could be bubbled up gracefully.
___
*[webapp/models/path/segments.go, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkHh-W-CWKQVgbBpLH:-MwkHh-W-CWKQVgbBpLI:bvnitxo) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/models/path/segments.go#L72)):*
> ```Go
> 	}
> 	srcIa, _ := addr.IAFrom(srcI, srcA) // ignore invalid range of AS error
> 	dstIa, _ := addr.IAFrom(dstI, dstA) // ignore invalid range of AS error
> ```

Pass `srcIA` as IA directly? Then any possible error in `IAFrom` can be bubbled up.

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: all files reviewed, 15 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/addr.go, line 112 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwjzyQN5WCdwA775dA7:-MwklvMe9N_kLbCOJOpF:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L112)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

We don't need this. The tests that have previously constructed an `IA` directly should just use `MustParseIA`. As far as I remember, the IA was only constructed directly because at the time this `MustParseIA` had not been added yet.
</blockquote></details>

Done.
___
*[pkg/pan/addr.go, line 124 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk6SDOCb32U0UA0hj1:-MwkcJ0Z1ryXESVUb_zD:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L124)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Or just `addr.IA(ia).IsWildcard()`.
</blockquote></details>

Done.
___
*[pkg/pan/addr_test.go, line 31 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkB9XU2xmo9cKds8EX:-Mwkd4_f4MU84_vmMxeZ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr_test.go#L31)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Parse from string as suggested above, `ia := pan.MustParseIA("1-ff00:0:ff")` and `iaWildcard := pan.MustParseIA("1-0")`
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 63 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk4IAJAXPdYMlTD1db:-Mwkm7_sDSJZ-CKcwjTi:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L63)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

These type checks make me cry a little bit. We'll need to revisit this, these new path types make things even more complicated than before. E.g. there is at least one more way an empty path could be represented (`RawReplyPath` containing a `slayers/path/empty.Path`).

This `IsEmpty` is currently only used internally in pan, only`reversePathFromForwardingPath`. Perhaps it would be best to remove this as a public function and so avoid having to make this work for all possible representations of an empty path. 
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 77 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk3fiM1cBmtfUc34hK:-MwkdccL0hfEgJMbbupX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L77)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This `if` can just be the `default:` of the `switch` above.
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 82 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkEX1fC5LcsZE9Coio:-MwkeUL9Er5Ekb3uDRcX:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L82)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think this also needs to handle `snet.RawPath`
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 106 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkC1T_CfeOAaFeL0F-:-MwkgdNa6O19E6MwtqDl:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L106)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Let this `panic` here, we really expect this to be only called with `RawPath`.
Then the `IsEmpty` (removed, see above) can be inlined here by just `len(rp.Raw) == 0`.
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 127 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkEjetCFF8JYbASccN:-Mwkon2B1JxKLrP4NB_1:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L127)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This can only be called with an `snet.RawPath`. I think it would help to change the type here accordingly and type assert on the call sites.
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 154 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkCdG36EO0QhVNQcX3:-MwkgwNf2ipMyJbYXx97:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L154)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Rather change the signature of the function above to take these as values instead of pointers.
</blockquote></details>

Done.
___
*[pkg/pan/path.go, line 189 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkCq9YAm4mKFeg5Yov:-Mwkh81uC9tWTvJ0OVEq:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/path.go#L189)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Also here, change the signature of `first` and `second` to take hf by value.
</blockquote></details>

Done.
___
*[pkg/pan/internal/ping/ping.go, line 147 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkF3uNDwRiUw8jthOi:-MwkpIIaAvACsZk4AiQp:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/internal/ping/ping.go#L147)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This will always be `snet.RawPath`. Maybe we can make this explicit here (type assert when filling the struct).
</blockquote></details>

Done.
___
*[pkg/pan/internal/ping/ping.go, line 169 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkFt1LEJxhIOkb_JjL:-MwkmruU1rTplSqEDYVb:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/internal/ping/ping.go#L169)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

It turns out these `Path` members are actually not used (we only inspect the `Path` of the `Reply` struct instead) and can be removed.
</blockquote></details>

Done.
___
*[webapp/lib/sciond.go, line 196 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mwk5QiD2k9hhGJz-pFY:-MwkhZ7C1NoBb8fF4Cvt:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/lib/sciond.go#L196)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Left over debug statement?
</blockquote></details>

Done.
___
*[webapp/models/path/segments.go, line 40 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkHE93E8t0SH8eCp5A:-MwkjVsaDtDOkMszHYya:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/models/path/segments.go#L40)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just remove this function?
In two cases, using this function only makes things longer because the existing IA is split into ISD/AS first.
In the third case, the error from `IAFrom` could be bubbled up gracefully.
</blockquote></details>

Done.
___
*[webapp/models/path/segments.go, line 72 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwkHh-W-CWKQVgbBpLH:-Mwkk6xR0tDxjWsjyJhu:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/webapp/models/path/segments.go#L72)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Pass `srcIA` as IA directly? Then any possible error in `IAFrom` can be bubbled up.
</blockquote></details>

Done.

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: all files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/addr.go, line 112 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwjzyQN5WCdwA775dA7:-MwlILU44WvknfKRT0cd:bvgs8k) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L112)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Almost, the now unused function `IAFrom` is still here.
___
*[webapp/models/path/segments.go, line 57 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwlJd4-1OjVSzW9t50S:-MwlJd40370Ujx_2vpPP:b-73il6z) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/aff0c17a3fce7d62fcf4b19d04e193a476c9af09/webapp/models/path/segments.go#L57)):*
> ```Go
> 	for _, ase := range theseg.ASEntries {
> 		hof := ase.HopEntry.HopField
> 		ia, _ := addr.IAFrom(ase.Local.ISD(), ase.Local.AS()) // ignore error
> ```

Isn't this just `ase.Local`?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: 14 of 20 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[pkg/pan/addr.go, line 112 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwjzyQN5WCdwA775dA7:-MwlOtnv0buV4ZIZ_SRh:b8pktxv) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9eef280ce30a91be33935ca35e0df4b8e3a61e67/pkg/pan/addr.go#L112)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Almost, the now unused function `IAFrom` is still here.
</blockquote></details>

done done.
___
*[webapp/models/path/segments.go, line 57 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-MwlJd4-1OjVSzW9t50S:-MwlO8bD5CdS48zJbKIC:bl06cvf) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/aff0c17a3fce7d62fcf4b19d04e193a476c9af09/webapp/models/path/segments.go#L57)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Isn't this just `ase.Local`?
</blockquote></details>

Done. (facepalm)

**Review by matzf — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[.circleci/config.yml, line 34 at r3](https://reviewable.io/reviews/netsec-ethz/scion-apps/222#-Mx3MiAKDPdCRP-ggq-t:-Mx3MiAKDPdCRP-ggq-u:bj9ufjz) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/9597667bcc4485109d6d33ed767f6183f04e8ee7/.circleci/config.yml#L34)):*
> ```YAML
>           key: v2-pkg-cache-{{ checksum "go.sum" }}
>           paths:
>             - "/go/pkg"
> ```

This path is empty, cache is not working. With the `cimg/go` images, this should be `~/go/pkg` and perhaps also `~/.cache/go-build`. 
Could you please adapt this and bump the cache key?

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by juagargi — COMMENTED** [review]
> Reviewed 5 of 19 files at r1, 8 of 10 files at r2, 3 of 6 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/222)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
