### PR TITLE
Extend Skip functionality for latest scion-browser extension

### PR DESCRIPTION
**Pull request by martenwallewein**
Hey ho,

this PR adds some functionality to the skip proxy (e.g. support for TCP/SCION proxying, hostname resolution, etc) that we implemented for the hotnets 2022 paper. 

Cheers,
Marten

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233)

### CODE REVIEW

**Review by JordiSubira — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233)* status: 0 of 1 files reviewed, 2 unresolved discussions / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`skip/main.go` line 87 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/233#-N8d2INd8RkZRMSxxjf8:-N8d2INe19e2fTR92D07:bge5w3f) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e4a51069fa1e1e28168928aa7fb070704e434c5/skip/main.go#L87)):*
> ```Go
> 	apiMux.HandleFunc("/r", handleRedirectBackOrError)
> 
> 	apiMux.HandleFunc("/resolve", handleHostResolutionRequest)
> ```

We might remove this handler, if we are using the "/r" to do the "scionEnabled" domain classification.
___
*[`skip/main.go` line 192 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/233#-N8dDo1H93rAHkNieTMr:-N8dDo1H93rAHkNieTMs:b-lbjtxz) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e4a51069fa1e1e28168928aa7fb070704e434c5/skip/main.go#L192)):*
> ```Go
> 	if err != nil {
> 		fmt.Println("verbose: ", err.Error())
> 		ok := errors.As(err, &pan.HostNotFoundError{})
> ```

Replace with 



_Code snippet:_
```Go
ok := errors.As(err, &pan.HostNotFoundError{})
```

**Comment by martenwallewein** [comment]
I've checked this again, since I've trouble replying to the two change requests, I need to write it here. 

1) I've double checked the removal of the "/resolve" handler and it's not possible. Deriving the scionEnabled State from redirecting would only work for strict mode, in all other cases we would loose these information. So we need to keep this handler for now.

2) Done. 

So from my side we could merge this thing and plan the next steps for the extension.

**Review by JordiSubira — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233)* status: 0 of 1 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained / 0 of 1 approvals obtained

___
*[`skip/main.go` line 87 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/233#-N8d2INd8RkZRMSxxjf8:-NEGLzfR1oJOJF70xrFm:ba8tmou) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e4a51069fa1e1e28168928aa7fb070704e434c5/skip/main.go#L87)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

We might remove this handler, if we are using the "/r" to do the "scionEnabled" domain classification.
</blockquote></details>

Just to summarize the rational here: the "/r" handler is used to redirect the first request to domains accessed in strict-mode (either in global strict or specified), while the `/resolve` handler is used to check whether a domain is accessible via `SCION`. This request is asynchronous w.r.t. to the HTTP request triggering it. The SKIP proxy will decide under the hood where to forward the primary request. On the other hand, the `/resolve` response information is used to print out whether the information is fetched via SCION or BGP/IP.

**Review by JordiSubira — COMMENTED** [review]
:lgtm: 

1. Is summarized above.

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233#-:-NEGNDgw59m2deWX65nK:b-48ghn8)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by JordiSubira — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233#-:-NEGNNOMA2P2Y9bWHzj7:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by JordiSubira — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233)* status: all files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained, and 1 stale / 0 of 1 approvals obtained

**Review by JordiSubira — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/233)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
