### PR TITLE
Bump scion and rains dependencies

### PR DESCRIPTION
**Pull request by marcfrei**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
:lgtm: 

Note: some previous discussion in #166.

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-:-MMPoJI88gXfj2hB3MW5:byqg6bd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r5, 3 of 6 files at r6, 2 of 2 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-:-MO0R9Vi4jr9rI42igXV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171)* status: all files reviewed, 1 unresolved discussion (waiting on @marcfrei)

___
*[.circleci/config.yml, line 35 at r8](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-MO0TR1m5oN3CSQFJxdC:-MO0TR1o26VMfLPOj0iP:bkn141f) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e12dc725293727ccc65452096b053434993f7c0/.circleci/config.yml#L35)):*
> ```
> ubuntu-1604:202007-01
> ```

Could we use the newer image `ubuntu-2004:202008-01`, aka `ubuntu-2004:202010-01`?

**Comment by marcfrei** [comment]
___
*[.circleci/config.yml, line 35 at r8](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-MO0TR1m5oN3CSQFJxdC:-MO0XPGU54A2CVLeCmCM:bij3tf6) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e12dc725293727ccc65452096b053434993f7c0/.circleci/config.yml#L35)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> ```
> ubuntu-1604:202007-01
> ```

Could we use the newer image `ubuntu-2004:202008-01`, aka `ubuntu-2004:202010-01`?
</blockquote></details>

Unfortunately, the new image comes with go 1.15, which breaks topology generation. What do you think, should we install go 1.14 on ubuntu-2004:202010-01 or should we just stick with ubuntu-1604:202007-01 for the time being?

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @marcfrei and @matzf)

___
*[.circleci/config.yml, line 35 at r8](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-MO0TR1m5oN3CSQFJxdC:-MO0ZziW1WXJCxCOB8W3:btm7a6f) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e12dc725293727ccc65452096b053434993f7c0/.circleci/config.yml#L35)):*
>should we just stick with ubuntu-1604:202007-01 for the time being

let's stick with the older image and do the switch later together with the change to Go 1.15+
Would have been nice though.

**Comment by marcfrei** [comment]
___
*[.circleci/config.yml, line 35 at r8](https://reviewable.io/reviews/netsec-ethz/scion-apps/171#-MO0TR1m5oN3CSQFJxdC:-MO0wySY-tOgUGTxBniw:bm5oqhg) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/2e12dc725293727ccc65452096b053434993f7c0/.circleci/config.yml#L35)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

>should we just stick with ubuntu-1604:202007-01 for the time being

let's stick with the older image and do the switch later together with the change to Go 1.15+
Would have been nice though.
</blockquote></details>

I agree, thanks!

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/171)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
