### PR TITLE
hellodrkey example

### PR DESCRIPTION
**Pull request by juagargi**
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)

### CODE REVIEW

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/hellodrkey.go, line 54 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwHky2KQvVG4rx-R2:-MOpwHkz9UiO5oZjC6ED:b5qgcok) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L54)):*
> ```Go
> func NewClient(sciondPath string) Client {
> 	sciond, err := sciond.NewService(sciondPath).Connect(context.Background())
> ```

Remove this empty line or add one in `NewServer` for consistency?

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/hellodrkey.go, line 126 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwaCGA2ufpFJkTaiF:-MOpwaCGA2ufpFJkTaiG:bqgl61j) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L126)):*
> ```Go
> }
> 
> func (s Server) HostKey(meta drkey.Lvl2Meta) drkey.Lvl2Key {
> ```

Not used, right? Maybe remove this function to keep the example minimal?

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/hellodrkey.go, line 151 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwn1d-KPP-PYSKrGN:-MOpwn1d-KPP-PYSKrGO:bbr6xqp) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L151)):*
> ```Go
> 	clientKey = client.HostKey(metaClient)
> 
> 	durationClient := time.Since(t0)
> ```

Move this statement before the empty line?

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/hellodrkey.go, line 29 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpx-Ff5G68ftJSkLG8:-MOpx-Ff5G68ftJSkLG9:b9j2x1o) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L29)):*
> ```Go
> )
> 
> var now = time.Now().UTC()
> ```

I didn't quite get why this is global var. Could we also keep it local to main and pass it around via function params?

**Comment by marcfrei** [comment]
*[a discussion](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpxQf4AAzFqQ2_Xepj:-MOpxQf4AAzFqQ2_Xepk:bocad78) (no related file):*
I like the example because it is really minimal.

I already know the DRKey system a little bit from Lightning Filter and had no problem to understand what is going on here. Users with no prior knowledge will obviously have a harder time to understand the motivation for this example. What would be the best reference to get them started?

- Does it make sense to maintain the new "invariant" (introduced during the SCIONLab update) that all examples have a README.md and that every example is also shortly referenced from the main README.md?

- Maybe it would be helpful to also add a quick note to this example's README on how to generate the topology this example is expecting.

---

**Review by marcfrei — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: all files reviewed, 5 unresolved discussions (waiting on @juagargi)

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @marcfrei)

*[a discussion](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpxQf4AAzFqQ2_Xepj:-MOqf-Iq6KHXIaPMsJAN:b4vjrgr) (no related file):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

I like the example because it is really minimal.

I already know the DRKey system a little bit from Lightning Filter and had no problem to understand what is going on here. Users with no prior knowledge will obviously have a harder time to understand the motivation for this example. What would be the best reference to get them started?

- Does it make sense to maintain the new "invariant" (introduced during the SCIONLab update) that all examples have a README.md and that every example is also shortly referenced from the main README.md?

- Maybe it would be helpful to also add a quick note to this example's README on how to generate the topology this example is expecting.
</blockquote></details>

Thanks for the review. Indeed much more documentation was needed. I followed your advice and added the README with a description of what `hellodrkey` does, and how to configure the `gen` directory for it to run.

---
___
*[_examples/hellodrkey/hellodrkey.go, line 29 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpx-Ff5G68ftJSkLG8:-MOqUZSb9DlNJNqC2mcv:bsvp3xt) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L29)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

I didn't quite get why this is global var. Could we also keep it local to main and pass it around via function params?
</blockquote></details>

Like for the other meta parameters (`srcIA`, etc) it was specified here, to simplify the rest of the code. It should be a constant value, and the same for both the slow and fast path. 
Since we cannot have constants that are not strings, ints, etc, I decided to create private functions that return the value. The intention of it being a constant _might_ be more clear now.
Note the comment on the `timestamp` function.
___
*[_examples/hellodrkey/hellodrkey.go, line 54 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwHky2KQvVG4rx-R2:-MOq_Ibp3ltzMs6-PFfE:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L54)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove this empty line or add one in `NewServer` for consistency?
</blockquote></details>

Done.
___
*[_examples/hellodrkey/hellodrkey.go, line 126 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwaCGA2ufpFJkTaiF:-MOqaZj5714FnnyGn9Rh:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L126)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Not used, right? Maybe remove this function to keep the example minimal? 
</blockquote></details>

Done.
___
*[_examples/hellodrkey/hellodrkey.go, line 151 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpwn1d-KPP-PYSKrGN:-MOq_KVDCWksTr1fPiWz:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/1a7feaa36ccd6ef328337a24093a284e9c77efff/_examples/hellodrkey/hellodrkey.go#L151)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Move this statement before the empty line?
</blockquote></details>

Done.

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/README.md, line 22 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOqhFy_3vNGsfA6rKi6:-MOqhFy_3vNGsfA6rKi7:b-eg6w71) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/54732dba576fd281762a212930f23b70b603edb0/_examples/hellodrkey/README.md#L22)):*
> ```Markdown
> 
> Both slow and fast paths should obtain the same key.
> And both slow and fast path are measure for performance and their times displayed at the end.
> ```

"measured" instead of "measure"?

**Comment by marcfrei** [comment]
*[a discussion](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOpxQf4AAzFqQ2_Xepj:-MOqhSlL2WrlZx4fYonZ:bmayz4o) (no related file):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Thanks for the review. Indeed much more documentation was needed. I followed your advice and added the README with a description of what `hellodrkey` does, and how to configure the `gen` directory for it to run.
</blockquote></details>

Thanks, Juan. I think the new README is very helpful.

---

**Review by marcfrei — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @juagargi)

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/hellodrkey.go, line 34 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOqjWGpBhNhvJKV6LCf:-MOqjWGpBhNhvJKV6LCg:bud3ddp) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/54732dba576fd281762a212930f23b70b603edb0/_examples/hellodrkey/hellodrkey.go#L34)):*
> ```Go
> )
> 
> // should return the same timestamp everytime that it's called, but for simplicity we just
> ```

Maybe "Should" instead of "should"?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @juagargi and @marcfrei)

___
*[_examples/hellodrkey/README.md, line 22 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOqhFy_3vNGsfA6rKi6:-MOqkftb5vWh_US9yWzj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/54732dba576fd281762a212930f23b70b603edb0/_examples/hellodrkey/README.md#L22)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

"measured" instead of "measure"?
</blockquote></details>

Done.

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @marcfrei)

___
*[_examples/hellodrkey/hellodrkey.go, line 34 at r2](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOqjWGpBhNhvJKV6LCf:-MOqm3CgEnUWIO1MxO3v:bb7gzl0) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/54732dba576fd281762a212930f23b70b603edb0/_examples/hellodrkey/hellodrkey.go#L34)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Maybe "Should" instead of "should"?
</blockquote></details>

gone

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/README.md, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOrEVdY1ogFwS8M-f_m:-MOrEVdY1ogFwS8M-f_n:b-fpcfsl) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0adf347774ec0997b83a6b95c5ec642b75b11546/_examples/hellodrkey/README.md#L30)):*
> ```Markdown
> 
> 1. Create a local topology with the `tiny.topo` description: `./scion.sh topology -c ./topology/tiny.topo`.
> 1. Edit the CS configuration for `ff00:0:111` under `gen/ff00_0_111/cs1-ff00_0_111-1.toml`
> ```

`gen/ASff00_0_111/cs1-ff00_0_111-1.toml`

**Comment by marcfrei** [comment]
___
*[_examples/hellodrkey/README.md, line 48 at r3](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOrEyyxE-P8k2URUj9W:-MOrEyyxE-P8k2URUj9X:bobrenf) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0adf347774ec0997b83a6b95c5ec642b75b11546/_examples/hellodrkey/README.md#L48)):*
> ```Markdown
>    connection = "gen-cache/sd1-ff00_0_111.drkey.db"
>    ```
> 1. Edit the configuration for the CS in `gen/ff00_0_112/cs1-ff00_0_112-1.toml` and add:
> ```

`gen/ASff00_0_112/cs1-ff00_0_112-1.toml`

**Comment by marcfrei** [comment]
:lgtm:

**Comment by marcfrei** [comment]
I've tested the DRKey example with the configuration described in the new README: works perfectly -- just two small typos see below. Thank you very much!

**Review by marcfrei — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: all files reviewed, 3 unresolved discussions (waiting on @juagargi and @marcfrei)

**Review by juagargi — COMMENTED** [review]
:facepalm: Thanks for noticing the typos!!!

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-:-MOrKJ3K6oufwLceufuw:b-cod2qg)* status: all files reviewed, 3 unresolved discussions (waiting on @marcfrei)

___
*[_examples/hellodrkey/README.md, line 30 at r3](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOrEVdY1ogFwS8M-f_m:-MOrK6FY0dJVoZkTRn56:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0adf347774ec0997b83a6b95c5ec642b75b11546/_examples/hellodrkey/README.md#L30)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`gen/ASff00_0_111/cs1-ff00_0_111-1.toml`
</blockquote></details>

Done.
___
*[_examples/hellodrkey/README.md, line 48 at r3](https://reviewable.io/reviews/netsec-ethz/scion-apps/177#-MOrEyyxE-P8k2URUj9W:-MOrK75A5EHVXja9bXJf:b-896fix) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/0adf347774ec0997b83a6b95c5ec642b75b11546/_examples/hellodrkey/README.md#L48)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`gen/ASff00_0_112/cs1-ff00_0_112-1.toml`
</blockquote></details>

Done.

**Comment by marcfrei** [comment]
:lgtm:

**Review by marcfrei — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/177)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
