### PR TITLE
pan: fix broken SNI

### LINKED ISSUE #248: pan: SNI apparently currently broken, breaks TLS for web-gateway
The web-gateway is currently broken for TLS, because Server Name Identification (SNI) appears to have been inadvertently dropped from pan. The `host` argument to `DialQUIC` is no longer being processed.

https://github.com/netsec-ethz/scion-apps/blob/3afc9a9118080aa78e6a6435c06549a8a6c0bd23/pkg/pan/quic_dial.go#L53

### PR DESCRIPTION
**Pull request by benthor**
Set host string via TLS config. Fixes #248

- - -
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/249)

### CODE REVIEW

**Review by marcfrei — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/249#-:-NtWBV7x-y0EEA-OO1GH:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 1 LGTMs obtained

___
*[`pkg/pan/quic_dial.go` line 70 at r1](https://reviewable.io/reviews/netsec-ethz/scion-apps/249#-NtWBMf09qYhdg7lqpRh:-NtWBMf09qYhdg7lqpRi:b7q9a41) ([raw file](https://github.com/netsec-ethz/scion-apps/blob/11cdf44c0372958675279514fc039579c8dacda2/pkg/pan/quic_dial.go#L70)):*
> ```Go
> 
> 	// Enable SNI on underlying TLS connection
> 	// stolen from quic-go@v0.41.0/transport.go
> ```

based on



_Code quote:_
```Go
stolen from
```

**Review by JordiSubira — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/249#-:-NtWTmvP1baZ-cNsC32F:bg7igkv)* status: <span>:shipit:</span> complete! 2 of 1 LGTMs obtained

**Review by marcfrei — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/249)* status: 0 of 1 files reviewed, 1 unresolved discussion / 0 of 1 LGTMs obtained, and 2 stale / 0 of 1 approvals obtained

**Review by marcfrei — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-apps/249)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
